2021-04-11 20:59:22,266 INFO    MainThread:28458 [wandb_setup.py:_flush():69] setting env: {}
2021-04-11 20:59:22,266 INFO    MainThread:28458 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-11 20:59:22,267 INFO    MainThread:28458 [wandb_init.py:_log_setup():336] Logging user logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210411_205922-10w4tye0/logs/debug.log
2021-04-11 20:59:22,267 INFO    MainThread:28458 [wandb_init.py:_log_setup():337] Logging internal logs to /md0/home/btilmon/projects/learncfa_pytorch/wandb/run-20210411_205922-10w4tye0/logs/debug-internal.log
2021-04-11 20:59:22,267 INFO    MainThread:28458 [wandb_init.py:init():369] calling init triggers
2021-04-11 20:59:22,267 INFO    MainThread:28458 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-11 20:59:22,268 INFO    MainThread:28458 [wandb_init.py:init():418] starting backend
2021-04-11 20:59:22,268 INFO    MainThread:28458 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-11 20:59:22,287 INFO    MainThread:28458 [backend.py:ensure_launched():123] starting backend process...
2021-04-11 20:59:22,296 INFO    MainThread:28458 [backend.py:ensure_launched():128] started backend process with pid: 28471
2021-04-11 20:59:22,299 INFO    MainThread:28458 [wandb_init.py:init():423] backend started and connected
2021-04-11 20:59:22,301 INFO    MainThread:28458 [wandb_init.py:init():463] updated telemetry
2021-04-11 20:59:22,302 INFO    MainThread:28458 [wandb_init.py:init():482] communicating current version
2021-04-11 20:59:22,982 INFO    MainThread:28458 [wandb_init.py:init():487] got version response 
2021-04-11 20:59:22,982 INFO    MainThread:28458 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-11 20:59:23,177 INFO    MainThread:28458 [wandb_init.py:init():520] starting run threads in backend
2021-04-11 20:59:23,237 INFO    MainThread:28458 [wandb_run.py:_console_start():1524] atexit reg
2021-04-11 20:59:23,238 INFO    MainThread:28458 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-11 20:59:23,239 INFO    MainThread:28458 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-11 20:59:23,241 INFO    MainThread:28458 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-11 20:59:23,242 INFO    MainThread:28458 [wandb_init.py:init():544] run started, returning control to user process
2021-04-11 20:59:26,478 INFO    MainThread:28458 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-11 20:59:26,479 INFO    MainThread:28458 [wandb_run.py:_restore():1466] restore
2021-04-11 20:59:28,673 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-11 20:59:29,030 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 758
}

2021-04-11 20:59:29,198 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 2010
}

2021-04-11 20:59:29,410 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 758
  total_bytes: 2010
}

2021-04-11 20:59:29,513 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2010
  total_bytes: 2010
}

2021-04-11 20:59:29,615 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2010
  total_bytes: 2010
}

2021-04-11 20:59:29,718 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2010
  total_bytes: 2010
}

2021-04-11 20:59:29,820 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2010
  total_bytes: 2010
}

2021-04-11 20:59:29,923 INFO    MainThread:28458 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2010
  total_bytes: 2010
}

2021-04-11 20:59:31,073 INFO    MainThread:28458 [wandb_run.py:_show_files():1838] logging synced files
